"use client";
import { useState } from "react";
import { Images, X } from "lucide-react";
import { formatPropertyType, getPlaceholderImage } from "@/lib/utils";
interface Props { images?: string[]; propertyType: string; title: string; listingType?: string; }
export default function PropertyGallery({images,propertyType,title,listingType="sale"}:Props) {
  const source=images?.filter(Boolean)??[]; const display=source.length?source:[getPlaceholderImage(propertyType,0)]; const mosaic=Array.from({length:5},(_,index)=>display[index%display.length]); const [open,setOpen]=useState(false); const [selected,setSelected]=useState(0);
  return <><div className="overflow-hidden rounded-3xl bg-slate-100"><div className="relative aspect-[16/10] sm:hidden"><img src={display[0]} alt={title} className="h-full w-full object-cover"/><button type="button" onClick={()=>setOpen(true)} className="absolute bottom-3 right-3 inline-flex items-center gap-1.5 rounded-lg bg-black/65 px-3 py-2 text-xs font-semibold text-white"><Images className="h-4 w-4"/>{display.length} ảnh</button></div><div className="hidden h-[430px] grid-cols-5 grid-rows-2 gap-1 sm:grid"><button type="button" onClick={()=>{setSelected(0);setOpen(true)}} className="relative col-span-3 row-span-2 overflow-hidden text-left"><img src={mosaic[0]} alt={`${title} - ảnh 1`} className="h-full w-full object-cover transition hover:scale-105"/></button>{mosaic.slice(1).map((image,index)=><button type="button" key={`${image}-${index}`} onClick={()=>{setSelected(index+1);setOpen(true)}} className="overflow-hidden"><img src={image} alt={`${title} - ảnh ${index+2}`} className="h-full w-full object-cover transition hover:scale-105"/></button>)}<div className="pointer-events-none absolute left-4 top-4 flex gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold text-white ${listingType==="rent"?"bg-emerald-600":"bg-blue-600"}`}>{listingType==="rent"?"Cho thuê":"Mua bán"}</span><span className="rounded-full bg-slate-950/70 px-3 py-1 text-xs font-medium text-white">{formatPropertyType(propertyType)}</span></div><button type="button" onClick={()=>setOpen(true)} className="absolute bottom-4 right-4 inline-flex items-center gap-2 rounded-xl bg-white/95 px-4 py-2 text-sm font-semibold text-slate-900 shadow"><Images className="h-4 w-4"/>Xem tất cả {display.length} ảnh</button></div></div>{open&&<div role="dialog" aria-modal="true" aria-label="Thư viện ảnh" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/95 p-4"><button type="button" onClick={()=>setOpen(false)} className="absolute right-5 top-5 rounded-full bg-white/10 p-3 text-white" aria-label="Đóng thư viện"><X className="h-6 w-6"/></button><div className="max-h-full max-w-6xl"><img src={display[selected%display.length]} alt={`${title} - ảnh ${selected+1}`} className="max-h-[78vh] w-auto max-w-full rounded-xl object-contain"/><div className="mt-4 flex gap-2 overflow-x-auto">{display.map((image,index)=><button type="button" key={`${image}-${index}`} onClick={()=>setSelected(index)} className={`h-16 w-24 shrink-0 overflow-hidden rounded-lg border-2 ${selected%display.length===index?"border-white":"border-transparent opacity-60"}`}><img src={image} alt={`Chọn ảnh ${index+1}`} className="h-full w-full object-cover"/></button>)}</div></div></div>}</>;
}
