import type { PropertyResponse, RentalType } from "@shared/types";
import { Bath, Building2, Clock, DoorOpen, Droplets, Fingerprint, Layers, PawPrint, Plug, ShieldCheck, WashingMachine } from "lucide-react";
export const rentalLabels: Record<RentalType,string>={room:"Phòng trọ",serviced_apartment:"Căn hộ dịch vụ",house_share:"Ở ghép",entire_house:"Nhà nguyên căn"};
export const ruleLabels={curfew:"Có giờ đóng cửa",private_bathroom:"Phòng tắm riêng",allow_pets:"Cho nuôi thú cưng",has_mezzanine:"Có gác lửng",has_washing_machine:"Máy giặt",live_with_owner:"Ở cùng chủ",has_elevator:"Thang máy",fingerprint_lock:"Khóa vân tay"};
export const costLabels={electricity_per_kwh:"Điện",water_cost:"Nước",parking_fee_monthly:"Gửi xe",service_fee_monthly:"Dịch vụ",deposit_months:"Đặt cọc"};
export function RentalBadges({property}:{property:PropertyResponse}){return property.listing_type!=="rent"?null:<div className="flex flex-wrap gap-2 text-xs text-blue-800">{property.rental_type&&<span>{rentalLabels[property.rental_type]}</span>}{property.rental_rules?.has_mezzanine===true&&<span>• Có gác lửng</span>}{property.rental_rules?.allow_pets===true&&<span>• Cho nuôi thú cưng</span>}</div>}
const format=(value:number)=>value.toLocaleString("vi-VN");
export default function RentalDetails({property}:{property:PropertyResponse}){if(property.listing_type!=="rent")return null; const costs=property.rental_costs; const rules=property.rental_rules; const costCards=[{key:"electricity_per_kwh",label:"Điện",icon:Plug,value:costs?.electricity_per_kwh,detail:costs?.electricity_billing==="state_rate"?"Giá nhà nước":costs?.electricity_billing==="fixed"?"Đơn giá cố định":undefined,suffix:"đ/kWh"},{key:"water_cost",label:"Nước",icon:Droplets,value:costs?.water_cost,detail:costs?.water_unit==="per_person"?"Theo người/tháng":costs?.water_unit==="per_m3"?"Theo m³":undefined,suffix:"đ"},{key:"parking_fee_monthly",label:"Gửi xe",icon:Building2,value:costs?.parking_fee_monthly,suffix:"đ/tháng"},{key:"service_fee_monthly",label:"Dịch vụ",icon:ShieldCheck,value:costs?.service_fee_monthly,suffix:"đ/tháng"},{key:"deposit_months",label:"Đặt cọc",icon:ShieldCheck,value:costs?.deposit_months,suffix:"tháng"}].filter((card)=>card.value!=null); const ruleCards=Object.entries(ruleLabels).flatMap(([key,label])=>{const value=rules?.[key as keyof typeof ruleLabels]; if(value!==true)return []; const Icon=({curfew:Clock,private_bathroom:Bath,allow_pets:PawPrint,has_mezzanine:Layers,has_washing_machine:WashingMachine,live_with_owner:DoorOpen,has_elevator:Building2,fingerprint_lock:Fingerprint} as const)[key as keyof typeof ruleLabels]; return [{key,label,Icon}]});
 return <div className="space-y-5">{costCards.length>0&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xs"><h2 className="text-xl font-bold text-slate-900">Chi phí thuê minh bạch</h2><p className="mt-1 text-sm text-slate-500">Các khoản được chủ nhà cung cấp</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{costCards.map(({key,label,icon:Icon,value,detail,suffix})=><div key={key} className="rounded-2xl bg-slate-50 p-4"><Icon className="h-5 w-5 text-blue-600"/><p className="mt-3 text-xs font-medium text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900">{key==="deposit_months"?`${format(value!)} ${suffix}`:`${format(value!)} ${suffix}`}</p>{detail&&<p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>)}</div></section>}{ruleCards.length>0&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xs"><h2 className="text-xl font-bold text-slate-900">Tiện nghi đã xác nhận</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{ruleCards.map(({key,label,Icon})=><div key={key} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><Icon className="h-5 w-5 text-emerald-600"/><span className="text-sm font-medium text-slate-800">{label}</span></div>)}</div>{rules?.curfew===true&&rules.curfew_time&&<p className="mt-4 text-sm text-slate-600">Giờ đóng cửa: <strong>{rules.curfew_time}</strong></p>}{rules?.max_occupants!=null&&<p className="mt-2 text-sm text-slate-600">Tối đa <strong>{rules.max_occupants}</strong> người</p>}</section>}</div>;
}
