"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { PropertyResponse, RentalFilters, RentalType } from "@shared/types";
import { apiClient } from "@/lib/api";
import PropertyCard from "@/components/PropertyCard";
import { rentalLabels, ruleLabels } from "@/components/RentalDetails";
type Criteria = RentalFilters & { query: string; min: string; max: string };
const initial: Criteria = { query: "", min: "", max: "" };
export default function RentalsPage() {
 const [items,setItems]=useState<PropertyResponse[]>([]),[draft,setDraft]=useState<Criteria>(initial),[applied,setApplied]=useState<Criteria>(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[capped,setCapped]=useState(false); const input="w-full rounded-xl border bg-white p-3";
 async function search(next=0,criteria=applied){setBusy(true);setError("");try{const{query,min,max,...filters}=criteria;const params={...filters,listing_type:"rent" as const,min_price:min===""?undefined:Number(min),max_price:max===""?undefined:Number(max)};if(query.trim()||filters.near_landmark){const response=await apiClient.searchProperties({...params,query:[query.trim(),filters.near_landmark].filter(Boolean).join(" ")||"phòng cho thuê",limit:100});setItems(response.results.map(x=>x.property));setHasMore(false);setCapped(response.total>response.results.length)}else{const found=await apiClient.listProperties({...params,skip:next*20,limit:20});setItems(found);setHasMore(found.length===20);setCapped(false)}setPage(next)}catch(cause){setError(cause instanceof Error?cause.message:"Không thể tải tin cho thuê")}finally{setBusy(false)}}
 useEffect(()=>{void search(0,initial)},[]); const submit=()=>{setApplied(draft);void search(0,draft)};
 return <main className="mx-auto max-w-7xl space-y-8 p-6"><header><nav className="mb-5 flex gap-3"><Link className="rounded-full border px-5 py-2" href="/?listing_type=sale">Mua bán</Link><Link className="rounded-full bg-blue-700 px-5 py-2 text-white" href="/rentals">Cho thuê</Link></nav><h1 className="text-3xl font-bold">Phòng trọ & căn hộ dịch vụ</h1></header><form className="grid gap-4 rounded-2xl border bg-slate-50 p-5 sm:grid-cols-2 lg:grid-cols-3" onSubmit={e=>{e.preventDefault();submit()}}><label>Tìm kiếm<input className={input} value={draft.query} onChange={e=>setDraft({...draft,query:e.target.value})}/></label><label>Loại chỗ ở<select className={input} value={draft.rental_type??""} onChange={e=>setDraft({...draft,rental_type:(e.target.value||undefined)as RentalType|undefined})}><option value="">Tất cả</option>{Object.entries(rentalLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Gần địa điểm (3 km)<input className={input} value={draft.near_landmark??""} onChange={e=>setDraft({...draft,near_landmark:e.target.value||undefined})}/></label><label>Giá từ<input className={input} type="number" min="0" value={draft.min} onChange={e=>setDraft({...draft,min:e.target.value})}/></label><label>Giá đến<input className={input} type="number" min="0" value={draft.max} onChange={e=>setDraft({...draft,max:e.target.value})}/></label><label>Cọc tối đa<input className={input} type="number" min="0" step="1" value={draft.max_deposit??""} onChange={e=>setDraft({...draft,max_deposit:e.target.value===""?undefined:Number(e.target.value)})}/></label>{Object.entries(ruleLabels).map(([k,v])=><label key={k}>{v}<select className={input} value={draft[k as keyof RentalFilters]==null?"":String(draft[k as keyof RentalFilters])} onChange={e=>setDraft({...draft,[k]:e.target.value===""?undefined:e.target.value==="true"})}><option value="">Không giới hạn</option><option value="true">Có</option><option value="false">Không</option></select></label>)}<button disabled={busy} className="rounded-xl bg-blue-700 p-3 text-white">{busy?"Đang tìm…":"Tìm chỗ ở"}</button></form>{error&&<p role="alert" className="text-red-700">{error}</p>}<p>{items.length} tin trên trang {page+1}</p>{capped&&<p>Kết quả giới hạn 100 tin; hãy thu hẹp bộ lọc.</p>}<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(item=><PropertyCard key={item.id} item={item}/>)}</div><div className="flex gap-4"><button disabled={busy||page===0||Boolean(applied.query||applied.near_landmark)} onClick={()=>void search(page-1)}>Trang trước</button><button disabled={busy||!hasMore||Boolean(applied.query||applied.near_landmark)} onClick={()=>void search(page+1)}>Trang sau</button></div></main>;
}
