"use client";
import { z } from "zod";
import type { RentalCosts, RentalRules, RentalType } from "@shared/types";
import { rentalLabels, ruleLabels, costLabels } from "./RentalDetails";
const amount = z.number().int().min(0).nullable().optional();
export const rentalSchema = z.object({
 rental_type: z.enum(["room", "serviced_apartment", "house_share", "entire_house"]).nullable().optional(),
 rental_costs: z.object({ electricity_per_kwh: amount, water_cost: amount, parking_fee_monthly: amount, service_fee_monthly: amount, deposit_months: amount, electricity_billing: z.enum(["state_rate", "fixed"]).nullable().optional(), water_unit: z.enum(["per_m3", "per_person"]).nullable().optional() }).nullable().optional(),
 rental_rules: z.object({ curfew: z.boolean().nullable().optional(), private_bathroom: z.boolean().nullable().optional(), allow_pets: z.boolean().nullable().optional(), has_mezzanine: z.boolean().nullable().optional(), has_washing_machine: z.boolean().nullable().optional(), live_with_owner: z.boolean().nullable().optional(), has_elevator: z.boolean().nullable().optional(), fingerprint_lock: z.boolean().nullable().optional(), curfew_time: z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/).nullable().optional(), max_occupants: z.number().int().min(1).nullable().optional() }).nullable().optional().refine(value => value?.curfew !== false || value.curfew_time == null, { message: "curfew_time requires curfew=true" }),
});
export type RentalValue = { rental_type?: RentalType | null; rental_costs?: RentalCosts | null; rental_rules?: RentalRules | null };
export default function RentalForm({ value, onChange }: { value: RentalValue; onChange: (value: RentalValue) => void }) {
 const c = value.rental_costs ?? {}; const r = value.rental_rules ?? {};
 const input = "block w-full rounded-lg border p-2 mt-1 bg-white";
 return <fieldset className="rounded-2xl border bg-blue-50 p-5 space-y-4"><legend className="font-bold">Thông tin cho thuê</legend><p>Giá thuê tính bằng VND/tháng. Để trống nếu chưa rõ; nhập 0 khi miễn phí.</p><label>Loại phòng<select className={input} value={value.rental_type ?? ""} onChange={e => onChange({ ...value, rental_type: (e.target.value || null) as RentalType | null })}><option value="">Chưa cung cấp</option>{Object.entries(rentalLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4">{Object.entries(costLabels).map(([key,label]) => <label key={key}>{label}<input className={input} type="number" min="0" step="1" value={c[key as keyof typeof costLabels] ?? ""} onChange={e => onChange({ ...value, rental_costs: { ...c, [key]: e.target.value === "" ? null : Number(e.target.value) } })} /></label>)}<label>Tính điện<select className={input} value={c.electricity_billing ?? ""} onChange={e => onChange({ ...value, rental_costs: { ...c, electricity_billing: (e.target.value || null) as RentalCosts["electricity_billing"] } })}><option value="">Chưa cung cấp</option><option value="state_rate">Giá nhà nước</option><option value="fixed">Đơn giá cố định</option></select></label><label>Tính nước<select className={input} value={c.water_unit ?? ""} onChange={e => onChange({ ...value, rental_costs: { ...c, water_unit: (e.target.value || null) as RentalCosts["water_unit"] } })}><option value="">Chưa cung cấp</option><option value="per_m3">đ/m³</option><option value="per_person">đ/người/tháng</option></select></label>{Object.entries(ruleLabels).map(([key,label]) => <label key={key}>{label}<select className={input} value={r[key as keyof typeof ruleLabels] == null ? "" : String(r[key as keyof typeof ruleLabels])} onChange={e => onChange({ ...value, rental_rules: { ...r, [key]: e.target.value === "" ? null : e.target.value === "true" } })}><option value="">Chưa cung cấp</option><option value="true">Có</option><option value="false">Không</option></select></label>)}<label>Giờ đóng cửa<input className={input} type="time" value={r.curfew_time ?? ""} onChange={e => onChange({ ...value, rental_rules: { ...r, curfew_time: e.target.value || null } })}/></label><label>Số người tối đa<input className={input} type="number" min="1" step="1" value={r.max_occupants ?? ""} onChange={e => onChange({ ...value, rental_rules: { ...r, max_occupants: e.target.value === "" ? null : Number(e.target.value) } })}/></label></div></fieldset>;
}
